export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE";

export const ADIDAS_TYPE="ADIDAS_TYPE";
export const BATA_TYPE="BATA_TYPE";
export const PUMA_TYPE="PUMA_TYPE";




